#
###################################
# Site wide configuration
####################################
#
title: Jonathan Chang | Art, Culture, Data
email: jonathan@unibit.ai
description: "Jonathan Chang's blog on travel, media, technology. I'm a tech product manager. Former Yale undergrad, Univ. of Central Asia staffer, strategy consultant."
keywords: ["Jonathan Chang", "jchang", "Product Manager", "blog", "videos", "d3", "Python", "Data visualizations", "coding", "Yale", "consulting", "UCA", "vlog", "Youtube"]

#
###################################
# Jekyll configuration
####################################
#
timezone: America/New_York
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
permalink: /:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Jonathan Chang
  avatar: kumbel.jpg
  job:
  bio:
  email: jchangme@gmail.com
  disqus-shortname:
  twitter: iamjchang #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-39387429-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: TheGoldenRatio #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: jchangme #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: UCLAQkuhlifPC4BLYOOcnZAw
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username


#
###################################
# Plugins
####################################
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
